sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6tj5mgF6XPoL2Z2wUp
    access-key-secret: AX8zekoUPAdHHJn4ATeLRQ8SueLPpm
    bucket-name: food-take-away
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx517a0f533007d759
    secret: 83ffc7db997c8d1ec9b900e9a9cfc5ac
