sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAl5tPmhypxrw3ui54FeK6q
    access-key-secret: iilQYHHOkh6YKAKY4Z10zzXZU8q3tg
    bucket-name: web-tlias-311
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx517a0f533007d759
    secret: 83ffc7db997c8d1ec9b900e9a9cfc5ac
